version: "3"
services:
    jekyll:
        image: jekyll/jekyll:latest
        container_name: jinnabalu
        command: jekyll serve --force_polling
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll